import { Check, Copy, FileText, ThumbsDown, ThumbsUp } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Button } from './ui/Button'
import { Card } from './ui/Card'
import { Tooltip } from './ui/Tooltip'

export default function AIMessage({ content, detail, onToast }: { content:string; detail?:string; onToast:(s:string)=>void }) {
  const [copied,setCopied]=useState(false); const [vote,setVote]=useState<'up'|'down'|null>(null)
  const copy=async()=>{ await navigator.clipboard?.writeText(`${content} ${detail??''}`); setCopied(true); onToast('Answer copied to clipboard'); setTimeout(()=>setCopied(false),1500) }
  return <motion.div initial={{ opacity:0, y:12 }} animate={{ opacity:1, y:0 }} transition={{ duration:.3 }} className="flex max-w-3xl gap-3"><div className="mt-1 hidden h-9 w-9 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 text-xs font-bold text-white sm:grid">AI</div><Card className="min-w-0 flex-1 overflow-hidden"><div className="p-5 sm:p-6"><p className="text-sm font-semibold leading-6 text-slate-900">{content}</p>{detail && <p className="mt-3 text-sm leading-6 text-slate-600">{detail}</p>}<div className="mt-5 flex items-center gap-3 rounded-xl border border-blue-100 bg-blue-50/80 p-3.5"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white text-blue-600 shadow-sm"><FileText size={16} /></span><div className="min-w-0"><p className="truncate text-xs font-semibold text-blue-800">Leave Policy.pdf</p><p className="text-[10px] text-blue-600">Page 14 · Section 3.2</p></div><span className="ml-auto rounded-full bg-white px-2 py-1 text-[10px] font-bold text-blue-700">SOURCE</span></div></div><div className="flex items-center border-t border-slate-100 px-4 py-2"><time className="text-[10px] text-slate-400">10:30 AM</time><div className="ml-auto flex gap-1"><Tooltip label="Copy answer"><Button variant="ghost" size="icon" className="h-8 w-8" onClick={copy} aria-label="Copy answer">{copied?<Check size={14} className="text-emerald-600"/>:<Copy size={14}/>}</Button></Tooltip><Tooltip label="Helpful"><Button variant="ghost" size="icon" className={`h-8 w-8 ${vote==='up'?'bg-blue-50 text-blue-600':''}`} onClick={()=>setVote('up')} aria-label="Mark helpful"><ThumbsUp size={14}/></Button></Tooltip><Tooltip label="Not helpful"><Button variant="ghost" size="icon" className={`h-8 w-8 ${vote==='down'?'bg-red-50 text-red-600':''}`} onClick={()=>setVote('down')} aria-label="Mark not helpful"><ThumbsDown size={14}/></Button></Tooltip></div></div></Card></motion.div>
}
