import { Mic, Paperclip, Send, Square, X } from 'lucide-react'
import { motion } from 'framer-motion'
import { useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useApp } from '../context/AppContext'
import { Button } from './ui/Button'
import { Tooltip } from './ui/Tooltip'

type FormValues={question:string}
export default function ChatInput(){
  const {sendMessage,showToast}=useApp();const {register,handleSubmit,reset,watch,setValue}=useForm<FormValues>({defaultValues:{question:''}});const [recording,setRecording]=useState(false);const [attachment,setAttachment]=useState<File|null>(null);const fileRef=useRef<HTMLInputElement>(null)
  const submit=({question}:FormValues)=>{if(!question.trim())return;sendMessage(question.trim());reset();setAttachment(null)}
  const voice=()=>{if(recording)return;setRecording(true);showToast('Listening…');window.setTimeout(()=>{setValue('question','How many casual leaves are allowed?',{shouldDirty:true});setRecording(false);showToast('Voice input captured')},3000)}
  return <form onSubmit={handleSubmit(submit)} className="border-t border-slate-200 bg-white px-4 py-4 sm:px-6"><motion.div animate={recording?{boxShadow:['0 0 0 0 rgba(239,68,68,.15)','0 0 0 8px rgba(239,68,68,0)']}:undefined} transition={{repeat:recording?Infinity:0,duration:1.2}} className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_8px_30px_rgba(15,23,42,.08)] transition focus-within:border-blue-400 focus-within:ring-4 focus-within:ring-blue-50">{attachment&&<div className="mx-2 mb-1 flex items-center gap-2 rounded-lg bg-blue-50 px-3 py-2 text-[10px] font-semibold text-blue-700"><Paperclip size={13}/><span className="truncate">{attachment.name}</span><button type="button" onClick={()=>setAttachment(null)} className="ml-auto" aria-label="Remove attachment"><X size={13}/></button></div>}<textarea {...register('question')} rows={1} className="max-h-32 min-h-12 w-full resize-none bg-transparent px-3 py-2 text-sm text-slate-800 outline-none placeholder:text-slate-400" placeholder="Ask a question about HR policies..." aria-label="Question" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSubmit(submit)()}}}/><div className="flex items-center"><input ref={fileRef} type="file" className="hidden" accept=".pdf,.docx,.txt" onChange={e=>{const file=e.target.files?.[0];if(file){setAttachment(file);showToast('Attachment added')}}}/><Tooltip label="Attach a document"><Button type="button" variant="ghost" size="icon" className="h-9 w-9" aria-label="Attach document" onClick={()=>fileRef.current?.click()}><Paperclip size={17}/></Button></Tooltip><Tooltip label={recording?'Recording…':'Use voice input'}><Button type="button" variant="ghost" size="icon" className={`h-9 w-9 ${recording?'bg-red-50 text-red-600':''}`} aria-label="Voice input" onClick={voice}>{recording?<Square size={14} fill="currentColor"/>:<Mic size={17}/>}</Button></Tooltip>{recording&&<span className="ml-1 text-[10px] font-semibold text-red-600">Listening…</span>}<Button type="submit" size="sm" className="ml-auto h-10 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 px-4 shadow-lg shadow-blue-100" disabled={!watch('question').trim()}>Send <Send size={15}/></Button></div></motion.div><p className="mt-2.5 text-center text-[10px] text-slate-400">AI can make mistakes. Please verify important information.</p></form>
}
