import { Download, FileText, Highlighter } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { Button } from './ui/Button'
import { Modal } from './ui/Modal'

export default function DocumentPreviewModal(){
  const {selectedDocument,setSelectedDocument,retrievedDocuments,showToast}=useApp();if(!selectedDocument)return null
  const reference=retrievedDocuments.find(d=>d.id===selectedDocument.id)
  return <Modal open onClose={()=>setSelectedDocument(null)} title={selectedDocument.name}><div className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-500"><FileText size={19}/></span><div><p className="text-xs font-semibold">{selectedDocument.type} · {selectedDocument.size}</p><p className="text-[10px] text-slate-500">{selectedDocument.pages} pages · Updated {selectedDocument.updatedAt}</p></div></div><Button size="sm" onClick={()=>showToast('Mock download started')}><Download size={14}/> Download</Button></div><div className="relative mt-4 h-64 overflow-hidden rounded-xl border border-slate-200 bg-slate-100 p-5 shadow-inner"><div className="mx-auto h-full max-w-[320px] overflow-hidden bg-white p-6 shadow-sm"><div className="h-4 w-2/3 rounded bg-slate-200"/><div className="mt-5 space-y-2">{Array.from({length:8}).map((_,i)=><div key={i} className={`h-2 rounded ${reference&&i===3?'bg-yellow-300':'bg-slate-100'} ${i%3===0?'w-5/6':'w-full'}`}/>)}</div>{reference&&<div className="mt-5 flex items-center gap-2 rounded-lg border border-yellow-200 bg-yellow-50 p-2 text-[9px] font-semibold text-yellow-800"><Highlighter size={12}/> Referenced answer on page {reference.page}</div>}</div><span className="absolute bottom-3 right-3 rounded-full bg-slate-900 px-2.5 py-1 text-[9px] font-semibold text-white">Page {reference?.page??1} / {selectedDocument.pages}</span></div>{reference&&<div className="mt-4 grid grid-cols-3 gap-2">{[['Page',reference.page],['Section',reference.section],['Confidence',`${reference.score}%`]].map(([key,value])=><div key={key} className="rounded-xl border border-slate-200 p-3 text-center"><p className="text-[9px] uppercase tracking-wider text-slate-400">{key}</p><p className="mt-1 text-xs font-bold">{value}</p></div>)}</div>}</Modal>
}
