import { CheckCircle2, FileText, UploadCloud, X } from 'lucide-react'
import { useRef, useState, type DragEvent } from 'react'
import { motion } from 'framer-motion'
import { useApp } from '../context/AppContext'
import type { PolicyDocument } from '../types'
import { Button } from './ui/Button'
import { Modal } from './ui/Modal'

type UploadItem={id:string;file:File;progress:number;status:'ready'|'uploading'|'done'|'failed'}
export default function UploadDocumentsModal({open,onClose}:{open:boolean;onClose:()=>void}){
  const {addDocuments,showToast}=useApp();const [files,setFiles]=useState<UploadItem[]>([]);const inputRef=useRef<HTMLInputElement>(null);const [dragging,setDragging]=useState(false)
  const accept=(incoming:File[])=>{const valid=incoming.filter(file=>file.size<=20*1024*1024&&['pdf','docx','txt'].includes(file.name.split('.').pop()?.toLowerCase()??''));setFiles(prev=>[...prev,...valid.map(file=>({id:`file-${Date.now()}-${file.name}`,file,progress:0,status:'ready' as const}))]);if(valid.length<incoming.length)showToast('Upload failed: use PDF, DOCX, or TXT files under 20MB')}
  const drop=(e:DragEvent)=>{e.preventDefault();setDragging(false);accept(Array.from(e.dataTransfer.files))}
  const upload=()=>{if(!files.length)return;setFiles(prev=>prev.map(f=>({...f,status:'uploading'})));let progress=0;const interval=window.setInterval(()=>{progress+=10;setFiles(prev=>prev.map(f=>({...f,progress,status:progress>=100?'done':'uploading'})));if(progress>=100){window.clearInterval(interval);window.setTimeout(()=>{const docs:PolicyDocument[]=files.map(item=>({id:item.id,name:item.file.name,type:(item.file.name.split('.').pop()?.toUpperCase()??'TXT') as PolicyDocument['type'],size:`${(item.file.size/1024/1024).toFixed(1)} MB`,pages:Math.max(1,Math.round(item.file.size/50000)),category:'All Policies',updatedAt:'just now',uploaded:true}));addDocuments(docs)},250)}},120)}
  const close=()=>{setFiles([]);onClose()}
  return <Modal open={open} onClose={close} title="Upload documents"><div onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`grid min-h-40 place-items-center rounded-2xl border-2 border-dashed p-6 text-center transition ${dragging?'border-blue-500 bg-blue-50':'border-slate-200 bg-slate-50'}`}><div><motion.div animate={dragging?{y:[0,-5,0]}:{}} transition={{repeat:Infinity,duration:1}} className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-600"><UploadCloud size={23}/></motion.div><p className="mt-3 text-sm font-semibold">Drop files here or <button onClick={()=>inputRef.current?.click()} className="text-blue-600 hover:underline">browse</button></p><p className="mt-1 text-[10px] text-slate-500">PDF, DOCX or TXT · Maximum 20MB each</p><input ref={inputRef} type="file" multiple accept=".pdf,.docx,.txt" className="hidden" onChange={e=>accept(Array.from(e.target.files??[]))}/></div></div><div className="mt-4 max-h-52 space-y-2 overflow-y-auto">{files.map(item=><div key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-500">{item.status==='done'?<CheckCircle2 className="text-emerald-500" size={18}/>:<FileText size={17}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{item.file.name}</p><p className="text-[9px] text-slate-400">{(item.file.size/1024/1024).toFixed(2)} MB</p></div><button onClick={()=>setFiles(prev=>prev.filter(f=>f.id!==item.id))} className="text-slate-400 hover:text-red-500" aria-label={`Remove ${item.file.name}`}><X size={15}/></button></div>{item.status!=='ready'&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><motion.div className="h-full rounded-full bg-blue-600" animate={{width:`${item.progress}%`}}/></div>}</div>)}</div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={upload} disabled={!files.length||files.some(f=>f.status==='uploading')}>{files.every(f=>f.status==='done')?'Uploaded':'Upload files'}</Button></div></Modal>
}
